hw_quotes/hw_quotes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quotes.urls')),
    path('users/', include('users.urls')),
    path('author/', include('quotes.urls')),
]

hw_quotes/users/urls.py
from django.contrib.auth.views import LogoutView, LoginView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path
from .forms import LoginForm
from .views import RegisterView, ResetPass

app_name = 'users'

urlpatterns = [
    path('signup/', RegisterView.as_view(), name='register'),
    path('signin/', LoginView.as_view(
        template_name='users/signin.html',
        authentication_form=LoginForm,
        redirect_authenticated_user=True
    ), name='login'),
    path('logout/', LogoutView.as_view(
            template_name='users/logout.html',
        ), name='logout'),
    path('reset-password/', ResetPass.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

hw_quotes/users/models.py
from django.db import models

# Create your models here.

hw_quotes/users/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django import forms


class RegisterForm(UserCreationForm):
    username = forms.CharField(max_length=50, required=True, widget=forms.TextInput({'class': 'form-control'}))
    email = forms.CharField(max_length=50, required=True, widget=forms.EmailInput({'class': 'form-control'}))
    password1 = forms.CharField(max_length=50, min_length=5, required=True,
                                widget=forms.PasswordInput({'class': 'form-control'}))
    password2 = forms.CharField(max_length=50, min_length=5, required=True,
                                widget=forms.PasswordInput({'class': 'form-control'}))

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]


class LoginForm(AuthenticationForm):
    username = forms.CharField(max_length=50, required=True, widget=forms.TextInput({'class': 'form-control'}))
    password = forms.CharField(max_length=50, min_length=5, required=True,
                               widget=forms.PasswordInput({'class': 'form-control'}))

    class Meta:
        model = User
        fields = ["username", "password"]

hw_quotes/users/views.py
from django.contrib.auth.views import PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import View
from django.contrib import messages

from .forms import RegisterForm


class ResetPass(SuccessMessageMixin, PasswordResetView):
    template_name = 'users/password_reset.html'
    email_template_name = 'users/password_reset_email.html'
    html_email_template_name = 'users/password_reset_email.html'
    success_url = reverse_lazy('users:password_reset_done')
    success_message = "An email with instructions to reset your password has been sent to %(email)s."
    subject_template_name = 'users/password_reset_subject.txt'

class RegisterView(View):
    form_class = RegisterForm
    template_name = 'users/signup.html'

    def get(self, request):
        return render(request, self.template_name, {"form": self.form_class})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            messages.success(request, f"Hello {username}! Your account has been created.")
            return redirect(to="users:login")
        return render(request, self.template_name, {'form': form})

hw_quotes/users/templates/users/logout.html
{% extends 'quotes/base.html' %}

{% block content %}

<h3>Good bye</h3>

{% endblock %}

hw_quotes/users/templates/users/password_reset.html
{% extends 'quotes/base.html' %}

{% block content %}

<h2>Password reset</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Request password reset</button>
</form>

{% endblock %}

hw_quotes/users/templates/users/password_reset_complete.html
{% extends 'quotes/base.html' %}

{% block content %}

    <h2>Password reset complete!</h2>

{% endblock %}

hw_quotes/users/templates/users/password_reset_confirm.html
{% extends 'quotes/base.html' %}

{% block content %}

<h2>Enter new password</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save new password</button>
</form>

{% endblock %}

hw_quotes/users/templates/users/password_reset_done.html
{% extends 'quotes/base.html' %}

{% block content %}

<h2>Password reset request sent</h2>
<p>We've emailed you with instructions on how to reset your password.</p>

{% endblock %}

hw_quotes/users/templates/users/password_reset_email.html
{% autoescape off %}
<body>
<p>Hi {{ user.username }},</p>
<p>You requested a password reset for your account. Please follow this link to set a new password:</p>
<p>
    <a href="{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}">
        {{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
    </a>
</p>
<p>If you didn't request a password reset, please ignore this email.</p>
<p>Thanks,</p>
<p>The Our Team</p>
{% endautoescape %}

hw_quotes/users/templates/users/signin.html
{% extends 'quotes/base.html' %}

{% block content %}

<h2>SignIn</h2>

{% if form.errors %}
<span class="alert alert-danger" role="alert">{{form.non_field_errors}}</span>
{% endif %}

{% if messages %}
<div>
    {% for message in messages %}
    <div {% if message.tags %} class="alert alert-{{ message.tags }}" {% endif %} role="alert">{{ message }}</div>
    {% endfor %}
</div>
{% endif %}

<form method="post">
    {% csrf_token %}

    <div class="row mb-4">
        <label>Username:</label>
        {{form.username}}
        <span>{{form.errors.username}}</span>
    </div>
    <div class="row mb-3">
        <label>Password:</label>
        {{form.password}}
        <span>{{form.errors.password}}</span>
    </div>
    <div class="small text-center">
        <a href="{% url 'users:password_reset' %}" class="text-center"><i>Forgot Password?</i></a>
    </div>
    <div class="d-grid gap-2 col-6 mx-auto">
        <button type="submit" class="btn btn-primary btn-sm">Submit</button>
        <button type="reset" class="btn btn-secondary btn-sm">Reset</button>
    </div>
</form>

{% endblock %}

hw_quotes/users/templates/users/signup.html
{% extends 'quotes/base.html' %}

{% block content %}

<h2>SignUp</h2>

{% if form.errors %}
<span class="alert alert-danger" role="alert">{{ form.non_field_errors }}</span>
{% endif %}

<form method="post">
    {% csrf_token %}

    <div class="row mb-4">
        <label>Username:</label>
        {{ form.username }}
        <span>{{ form.errors.username }}</span>
    </div>
    <div class="row mb-3">
        <label>Email:</label>
        {{ form.email }}
        <span>{{ form.errors.email }}</span>
    </div>
    <div class="row mb-3">
        <label>Password:</label>
        {{ form.password1 }}
        <span>{{ form.errors.password1 }}</span>
    </div>
    <div class="row mb-3">
        <label>Password:</label>
        {{ form.password2}}
        <span>{{ form.errors.password2 }}</span>
    </div>

    <div class="d-grid gap-2 col-6 mx-auto">
        <button type="submit" class="btn btn-primary btn-sm">Submit</button>
        <button type="reset" class="btn btn-secondary btn-sm">Reset</button>
    </div>
</form>

{% endblock %}